spring:
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
    security:
        jwt:
            secret-key: ${JWT_SECRET_KEY}
            expiration: 86400000 # a day
            #            expiration: 10000 # 10 seconds in milliseconds
            refresh-token:
                expiration: 604800000 # 7 days
    cors:
        allowed:
            origin: ${PLATFORM_URL}:${FRONTEND_PORT}
    profiles:
        active: ${SPRING_PROFILES_ACTIVE}
    application:
        name: TAB project
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
